services:
  - type: web
    name: betfetcher
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install playwright
      playwright install --with-deps
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

