services:
  - type: web
    name: betfetcher-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: UPDATE_INTERVAL
        value: "180"
      - key: API_URL
        value: ""

