services:
  - type: web
    name: betfetcher
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install
    startCommand: python main.py
