services:
  - type: web
    name: betfetcher
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: UPDATE_INTERVAL
        value: "180"
      - key: ENABLE_POLLING
        value: "0"
